///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KPE.Rx.Jetblue.Repo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JetblueRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("669c297e-5854-4d61-aa65-dbae306a93b9")]
    public partial class JetblueRepository : RepoGenBaseFolder
    {
        static JetblueRepository instance = new JetblueRepository();
        JetblueRepositoryFolders.JetblueUXAppFolder _jetblueux;

        /// <summary>
        /// Gets the singleton class instance representing the JetblueRepository element repository.
        /// </summary>
        [RepositoryFolder("669c297e-5854-4d61-aa65-dbae306a93b9")]
        public static JetblueRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JetblueRepository() 
            : base("JetblueRepository", "/", null, 0, false, "669c297e-5854-4d61-aa65-dbae306a93b9", ".\\RepositoryImages\\JetblueRepository669c297e.rximgres")
        {
            _jetblueux = new JetblueRepositoryFolders.JetblueUXAppFolder(this);
        }

#region Variables

        string _QueryString = "A";

        /// <summary>
        /// Gets or sets the value of variable QueryString.
        /// </summary>
        [TestVariable("bf378a39-158b-4577-8a63-18c2e1028a44")]
        public string QueryString
        {
            get { return _QueryString; }
            set { _QueryString = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("669c297e-5854-4d61-aa65-dbae306a93b9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The JetblueUX folder.
        /// </summary>
        [RepositoryFolder("88a341ba-a173-4933-bfca-2b09ba73a596")]
        public virtual JetblueRepositoryFolders.JetblueUXAppFolder JetblueUX
        {
            get { return _jetblueux; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class JetblueRepositoryFolders
    {
        /// <summary>
        /// The JetblueUXAppFolder folder.
        /// </summary>
        [RepositoryFolder("88a341ba-a173-4933-bfca-2b09ba73a596")]
        public partial class JetblueUXAppFolder : RepoGenBaseFolder
        {
            JetblueRepositoryFolders.MainNavFolder _mainnav;
            JetblueRepositoryFolders.BookingFolder _booking;

            /// <summary>
            /// Creates a new JetblueUX  folder.
            /// </summary>
            public JetblueUXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("JetblueUX", "/dom", parentFolder, 10000, null, true, "88a341ba-a173-4933-bfca-2b09ba73a596", "")
            {
                _mainnav = new JetblueRepositoryFolders.MainNavFolder(this);
                _booking = new JetblueRepositoryFolders.BookingFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88a341ba-a173-4933-bfca-2b09ba73a596")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88a341ba-a173-4933-bfca-2b09ba73a596")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MainNav folder.
            /// </summary>
            [RepositoryFolder("b7d84469-fe38-445a-be77-8f31e00ee34d")]
            public virtual JetblueRepositoryFolders.MainNavFolder MainNav
            {
                get { return _mainnav; }
            }

            /// <summary>
            /// The Booking folder.
            /// </summary>
            [RepositoryFolder("5fc8fe30-c431-496a-a367-f070c49ba0e5")]
            public virtual JetblueRepositoryFolders.BookingFolder Booking
            {
                get { return _booking; }
            }
        }

        /// <summary>
        /// The MainNavFolder folder.
        /// </summary>
        [RepositoryFolder("b7d84469-fe38-445a-be77-8f31e00ee34d")]
        public partial class MainNavFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new MainNav  folder.
            /// </summary>
            public MainNavFolder(RepoGenBaseFolder parentFolder) :
                    base("MainNav", ".//div[@class~'main-nav']/ul[#'jb-primary-links']", parentFolder, 10000, null, false, "b7d84469-fe38-445a-be77-8f31e00ee34d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b7d84469-fe38-445a-be77-8f31e00ee34d")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b7d84469-fe38-445a-be77-8f31e00ee34d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The BookingFolder folder.
        /// </summary>
        [RepositoryFolder("5fc8fe30-c431-496a-a367-f070c49ba0e5")]
        public partial class BookingFolder : RepoGenBaseFolder
        {
            JetblueRepositoryFolders.DepartFromFolder _departfrom;
            JetblueRepositoryFolders.ArriveAtFolder _arriveat;
            JetblueRepositoryFolders.SelectionModalFolder _selectionmodal;

            /// <summary>
            /// Creates a new Booking  folder.
            /// </summary>
            public BookingFolder(RepoGenBaseFolder parentFolder) :
                    base("Booking", ".//div[@class~'bookerWrapper']/div", parentFolder, 10000, null, false, "5fc8fe30-c431-496a-a367-f070c49ba0e5", "")
            {
                _departfrom = new JetblueRepositoryFolders.DepartFromFolder(this);
                _arriveat = new JetblueRepositoryFolders.ArriveAtFolder(this);
                _selectionmodal = new JetblueRepositoryFolders.SelectionModalFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5fc8fe30-c431-496a-a367-f070c49ba0e5")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5fc8fe30-c431-496a-a367-f070c49ba0e5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DepartFrom folder.
            /// </summary>
            [RepositoryFolder("cb5e6a64-8e52-473a-bb6a-9e921d19d4af")]
            public virtual JetblueRepositoryFolders.DepartFromFolder DepartFrom
            {
                get { return _departfrom; }
            }

            /// <summary>
            /// The ArriveAt folder.
            /// </summary>
            [RepositoryFolder("f471f291-00f2-42db-9e7d-51b3bd6f8796")]
            public virtual JetblueRepositoryFolders.ArriveAtFolder ArriveAt
            {
                get { return _arriveat; }
            }

            /// <summary>
            /// The SelectionModal folder.
            /// </summary>
            [RepositoryFolder("7d412172-1e65-41dd-bb6a-43ec523bb685")]
            public virtual JetblueRepositoryFolders.SelectionModalFolder SelectionModal
            {
                get { return _selectionmodal; }
            }
        }

        /// <summary>
        /// The DepartFromFolder folder.
        /// </summary>
        [RepositoryFolder("cb5e6a64-8e52-473a-bb6a-9e921d19d4af")]
        public partial class DepartFromFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fromimgInfo;
            RepoItemInfo _frominputInfo;

            /// <summary>
            /// Creates a new DepartFrom  folder.
            /// </summary>
            public DepartFromFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartFrom", ".//div[@class~'originDestinationSelect']//span[@class~'DepartBox']/ancestor::div[@class~'input_wrapper']", parentFolder, 10000, null, false, "cb5e6a64-8e52-473a-bb6a-9e921d19d4af", "")
            {
                _fromimgInfo = new RepoItemInfo(this, "FromImg", ".//img", 10000, null, "b01dcfda-17dd-4fd5-b985-5dccc41ab9b3");
                _frominputInfo = new RepoItemInfo(this, "FromInput", ".//inputtag", 10000, null, "8bdfd2f8-c675-4d3c-baa8-961e7bcfafe0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb5e6a64-8e52-473a-bb6a-9e921d19d4af")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb5e6a64-8e52-473a-bb6a-9e921d19d4af")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FromImg item.
            /// </summary>
            [RepositoryItem("b01dcfda-17dd-4fd5-b985-5dccc41ab9b3")]
            public virtual Ranorex.ImgTag FromImg
            {
                get
                {
                    return _fromimgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The FromImg item info.
            /// </summary>
            [RepositoryItemInfo("b01dcfda-17dd-4fd5-b985-5dccc41ab9b3")]
            public virtual RepoItemInfo FromImgInfo
            {
                get
                {
                    return _fromimgInfo;
                }
            }

            /// <summary>
            /// The FromInput item.
            /// </summary>
            [RepositoryItem("8bdfd2f8-c675-4d3c-baa8-961e7bcfafe0")]
            public virtual Ranorex.InputTag FromInput
            {
                get
                {
                    return _frominputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FromInput item info.
            /// </summary>
            [RepositoryItemInfo("8bdfd2f8-c675-4d3c-baa8-961e7bcfafe0")]
            public virtual RepoItemInfo FromInputInfo
            {
                get
                {
                    return _frominputInfo;
                }
            }
        }

        /// <summary>
        /// The ArriveAtFolder folder.
        /// </summary>
        [RepositoryFolder("f471f291-00f2-42db-9e7d-51b3bd6f8796")]
        public partial class ArriveAtFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toimgInfo;
            RepoItemInfo _toinputInfo;

            /// <summary>
            /// Creates a new ArriveAt  folder.
            /// </summary>
            public ArriveAtFolder(RepoGenBaseFolder parentFolder) :
                    base("ArriveAt", ".//div[@class~'originDestinationSelect']//span[@class~'ArriveBox']/ancestor::div[@class~'input_wrapper']", parentFolder, 10000, null, false, "f471f291-00f2-42db-9e7d-51b3bd6f8796", "")
            {
                _toimgInfo = new RepoItemInfo(this, "ToImg", ".//img", 10000, null, "7bba9bdb-0c97-48a3-ae53-799db72cad7c");
                _toinputInfo = new RepoItemInfo(this, "ToInput", ".//inputtag", 10000, null, "d9b439ad-e579-44a8-bb2e-dfd36004b7ac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f471f291-00f2-42db-9e7d-51b3bd6f8796")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f471f291-00f2-42db-9e7d-51b3bd6f8796")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ToImg item.
            /// </summary>
            [RepositoryItem("7bba9bdb-0c97-48a3-ae53-799db72cad7c")]
            public virtual Ranorex.ImgTag ToImg
            {
                get
                {
                    return _toimgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ToImg item info.
            /// </summary>
            [RepositoryItemInfo("7bba9bdb-0c97-48a3-ae53-799db72cad7c")]
            public virtual RepoItemInfo ToImgInfo
            {
                get
                {
                    return _toimgInfo;
                }
            }

            /// <summary>
            /// The ToInput item.
            /// </summary>
            [RepositoryItem("d9b439ad-e579-44a8-bb2e-dfd36004b7ac")]
            public virtual Ranorex.InputTag ToInput
            {
                get
                {
                    return _toinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ToInput item info.
            /// </summary>
            [RepositoryItemInfo("d9b439ad-e579-44a8-bb2e-dfd36004b7ac")]
            public virtual RepoItemInfo ToInputInfo
            {
                get
                {
                    return _toinputInfo;
                }
            }
        }

        /// <summary>
        /// The SelectionModalFolder folder.
        /// </summary>
        [RepositoryFolder("7d412172-1e65-41dd-bb6a-43ec523bb685")]
        public partial class SelectionModalFolder : RepoGenBaseFolder
        {
            JetblueRepositoryFolders.RegionFolder _region;
            JetblueRepositoryFolders.AirportFolder _airport;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new SelectionModal  folder.
            /// </summary>
            public SelectionModalFolder(RepoGenBaseFolder parentFolder) :
                    base("SelectionModal", ".//div[@class~'overlayContainer']", parentFolder, 10000, null, false, "7d412172-1e65-41dd-bb6a-43ec523bb685", "")
            {
                _region = new JetblueRepositoryFolders.RegionFolder(this);
                _airport = new JetblueRepositoryFolders.AirportFolder(this);
                _closeInfo = new RepoItemInfo(this, "Close", ".//a[@class~'airport_popup_close']", 10000, null, "c9ab5312-ec52-45e5-bb9e-61d3d010f351");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7d412172-1e65-41dd-bb6a-43ec523bb685")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7d412172-1e65-41dd-bb6a-43ec523bb685")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("c9ab5312-ec52-45e5-bb9e-61d3d010f351")]
            public virtual Ranorex.ATag Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("c9ab5312-ec52-45e5-bb9e-61d3d010f351")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Region folder.
            /// </summary>
            [RepositoryFolder("c9f08a15-362a-4f7c-84e3-9f2c77da1667")]
            public virtual JetblueRepositoryFolders.RegionFolder Region
            {
                get { return _region; }
            }

            /// <summary>
            /// The Airport folder.
            /// </summary>
            [RepositoryFolder("2e0c9b66-5956-4d49-9e9e-02afe7c87d86")]
            public virtual JetblueRepositoryFolders.AirportFolder Airport
            {
                get { return _airport; }
            }
        }

        /// <summary>
        /// The RegionFolder folder.
        /// </summary>
        [RepositoryFolder("c9f08a15-362a-4f7c-84e3-9f2c77da1667")]
        public partial class RegionFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Region  folder.
            /// </summary>
            public RegionFolder(RepoGenBaseFolder parentFolder) :
                    base("Region", ".//div[@class~'region-list-container']", parentFolder, 10000, null, false, "c9f08a15-362a-4f7c-84e3-9f2c77da1667", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c9f08a15-362a-4f7c-84e3-9f2c77da1667")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c9f08a15-362a-4f7c-84e3-9f2c77da1667")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The AirportFolder folder.
        /// </summary>
        [RepositoryFolder("2e0c9b66-5956-4d49-9e9e-02afe7c87d86")]
        public partial class AirportFolder : RepoGenBaseFolder
        {
            RepoItemInfo _airportcontainsInfo;
            RepoItemInfo _airportstartswithInfo;

            /// <summary>
            /// Creates a new Airport  folder.
            /// </summary>
            public AirportFolder(RepoGenBaseFolder parentFolder) :
                    base("Airport", ".//div[@class~'airports-list-container']", parentFolder, 10000, null, false, "2e0c9b66-5956-4d49-9e9e-02afe7c87d86", "")
            {
                _airportcontainsInfo = new RepoItemInfo(this, "AirportContains", ".//li[@class~'city']/a[@innertext~$QueryString]", 10000, null, "84582ff4-f5fe-4cf9-a75c-c0910b041318");
                _airportstartswithInfo = new RepoItemInfo(this, "AirportStartsWith", ".//li[@class~'city']/a[@innertext>$QueryString]", 10000, null, "ea98fd47-e1c6-40fe-95c4-628e255f3ef3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2e0c9b66-5956-4d49-9e9e-02afe7c87d86")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2e0c9b66-5956-4d49-9e9e-02afe7c87d86")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AirportContains item.
            /// </summary>
            [RepositoryItem("84582ff4-f5fe-4cf9-a75c-c0910b041318")]
            public virtual Ranorex.ATag AirportContains
            {
                get
                {
                    return _airportcontainsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AirportContains item info.
            /// </summary>
            [RepositoryItemInfo("84582ff4-f5fe-4cf9-a75c-c0910b041318")]
            public virtual RepoItemInfo AirportContainsInfo
            {
                get
                {
                    return _airportcontainsInfo;
                }
            }

            /// <summary>
            /// The AirportStartsWith item.
            /// </summary>
            [RepositoryItem("ea98fd47-e1c6-40fe-95c4-628e255f3ef3")]
            public virtual Ranorex.ATag AirportStartsWith
            {
                get
                {
                    return _airportstartswithInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AirportStartsWith item info.
            /// </summary>
            [RepositoryItemInfo("ea98fd47-e1c6-40fe-95c4-628e255f3ef3")]
            public virtual RepoItemInfo AirportStartsWithInfo
            {
                get
                {
                    return _airportstartswithInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}