///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KPE.Rx.Autoprac.Repo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutopracRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("3c2a055a-7ff1-4b7e-bbe3-45ec17ee02fe")]
    public partial class AutopracRepository : RepoGenBaseFolder
    {
        static AutopracRepository instance = new AutopracRepository();
        AutopracRepositoryFolders.AutopracUXAppFolder _autopracux;

        /// <summary>
        /// Gets the singleton class instance representing the AutopracRepository element repository.
        /// </summary>
        [RepositoryFolder("3c2a055a-7ff1-4b7e-bbe3-45ec17ee02fe")]
        public static AutopracRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutopracRepository() 
            : base("AutopracRepository", "/", null, 0, false, "3c2a055a-7ff1-4b7e-bbe3-45ec17ee02fe", ".\\RepositoryImages\\AutopracRepository3c2a055a.rximgres")
        {
            _autopracux = new AutopracRepositoryFolders.AutopracUXAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3c2a055a-7ff1-4b7e-bbe3-45ec17ee02fe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AutopracUX folder.
        /// </summary>
        [RepositoryFolder("1c30666c-6877-49de-96bf-80fb025f3336")]
        public virtual AutopracRepositoryFolders.AutopracUXAppFolder AutopracUX
        {
            get { return _autopracux; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class AutopracRepositoryFolders
    {
        /// <summary>
        /// The AutopracUXAppFolder folder.
        /// </summary>
        [RepositoryFolder("1c30666c-6877-49de-96bf-80fb025f3336")]
        public partial class AutopracUXAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new AutopracUX  folder.
            /// </summary>
            public AutopracUXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AutopracUX", "/dom[@domain~'automationpractice.com']", parentFolder, 10000, null, false, "1c30666c-6877-49de-96bf-80fb025f3336", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1c30666c-6877-49de-96bf-80fb025f3336")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1c30666c-6877-49de-96bf-80fb025f3336")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}