///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Jetblue
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JetblueRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("7d366307-8f2d-4f22-8ae9-d92e358d9cba")]
    public partial class JetblueRepository : RepoGenBaseFolder
    {
        static JetblueRepository instance = new JetblueRepository();

        /// <summary>
        /// Gets the singleton class instance representing the JetblueRepository element repository.
        /// </summary>
        [RepositoryFolder("7d366307-8f2d-4f22-8ae9-d92e358d9cba")]
        public static JetblueRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JetblueRepository() 
            : base("JetblueRepository", "/", null, 0, false, "7d366307-8f2d-4f22-8ae9-d92e358d9cba", ".\\RepositoryImages\\JetblueRepository7d366307.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7d366307-8f2d-4f22-8ae9-d92e358d9cba")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class JetblueRepositoryFolders
    {
    }
#pragma warning restore 0436
}